name: Build

on:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] 

    name: build-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: ./tools.py build shockwave-test --build-type ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: out/${{ env.BUILD_TYPE }}
      run: ctest --rerun-failed --output-on-failure

