name: Check format

on:
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-tooling

    - name: check format
      run: ./scripts/run-clang-format.py include/ src/ test/ -r

